---

# HOSTNAME            =  AerinAP-11
# SSID                =  11-AerinResortsWorld
# VLAN                =  11
# AUTHENTICATION      =  open
# KEY-MANAGEMENT      =  wpa
# WIFI-PASSWORD       =  C1sc0123
# CHANNEL             =  5
# ENCRYPTION          =  tkip

- name: AutoWifi
  hosts: aut
  gather_facts: no
  become: yes
  tasks:
    - name: Configuring SSID
      ios_command:
        commands:
          - conf t
          - hostname AerinAP-11
          - dot11 ssid 11-AerinResortsWorld
          - "vlan 11"
          - authentication open
          - authentication key-management wpa
          - wpa-psk ascii C1sc0123
          - guest-mode
          - default int dot11radio 0
          - default interface gigabitEthernet 0
          - end
      tags:
        - config

    - name: Deploying WIFI
      ios_command:
        commands:
          - conf t
          - int dot11radio 0
          - no shut
          - channel 5
          - encryption mode ciphers tkip
          - "encryption vlan 11 mode ciphers tkip"
          - ssid 11-AerinResortsWorld
          - end
      tags:
        - deploy

    - name: Connecting SSID to LAN
      ios_command:
        commands:
          - conf t
          - int dot11radio 0.11
          - "encapsulation dot1q 11 native"
          - bridge-group 1
          - end
      tags:
        - connect
